services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - local-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8280:8080"
    depends_on:
      - postgres
    networks:
      - local-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile.backend
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - local-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.backend
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - keycloak
      - eureka-server
    networks:
      - local-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.backend
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - KEYCLOAK_CLIENT_SECRET=PfSbqzShpIRAWTtqwYbCs2y44KaO9VVZ
    depends_on:
      - keycloak
      - user-service
      - eureka-server
    networks:
      - local-network

volumes:
  pg_data:

networks:
  local-network:
    name: local-network
