server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    # url: jdbc:postgresql://localhost:5432/local_db
    url: jdbc:postgresql://postgres:5432/local_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8280/realms/microservicos-realm

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
